<?php

declare(strict_types=1);

return [
    'prompt' => <<<'PROMPT'
Odczytaj dane pojazdu i dane polisy z załączonego pliku PDF z polisą.

W swoim wewnętrznym procesie myślowym najpierw znajdź w załączonym dokumencie wartości pól wymaganych w wynikowym obiekcie JSON, następnie wypisz wszystkie znalezione tak pary klucz-wartość, a następnie zwaliduj każdą taką parę na świeżo, ponownie, w oparciu o treść załączonej polisy.

Nie wymyślaj danych. Każde pole może mieć wartość pustego stringa "", jeśli nie da się go jednoznacznie potwierdzić w polisie. Stawiaj rzetelność i spójność danych ponad kompletność. Jeśli nie jesteś w stanie znaleźć wartości dla danego pola, zwróć pusty string "".

Zwróć wyłącznie wartości dla następujących pól:
  stan pojazdu - nowy luib używany,
  numer rejestracyjny,
  marka,
  model,
  wersja wyposażenia,
  vin,
  forma wlasnosci pojazdu - "Własny", "Leasing", "Bank", "Wynajem" lub synonim którejś z nich,
  rocznik - rok produkcji pojazdu,
  przebieg - w kilometrach,
  wartosc pojazdu brutto - w PLN,
  wartosc pojazdu netto - w PLN,
  kategoria pojazdu - osobowy, ciężarowy albo motocykl/inny,
  sposob korzystania - prywatny/standardowy/nietaxi albo taxi,
  typ silnika - benzynowy, diesel, elektryczny, hybryda albo CNG/LPG,
  pojemnosc silnika - w cm3,
  data nabycia,
  data pierwszej rejestracji - dotyczy tylko pojazdów używanych,
  planowana data rejestracji - dotyczy tylko pojazdów nowych,
  wspolposiadacz - flaga, czy polisa wskazuje więcej niż jednego właściciela/posiadacza pojazdu,
  imie wspolposiadacza,
  nazwisko wspolposiadacza,
  pesel wspolposiadacza,
  adres wspolposiadacza,
  pakiet ubezpieczeniowy - flaga, czy dokument dotyczy pakietu ubezpieczeniowego jako pojedynczego spójnego produktu/usługi, czy tylko listy produktów jak AC, NNW, Assistance, GAP albo Przedłużona Gwarancja,
  rodzaj assistance - zakres ochrony: minimalny, tylko na Polskę, na Europę z wyszczególnieniem kilometrażu, inne lub brak,
  towarzystwo ubezpieczeniowe - nazwa TU, które wystawiło polisę,
  nr polisy - pełny alfanumeryczny kod/numer/id polisy,
  data konca polisy,
  cena przedluzonej gwarancji,
  pochodzenie polisy,
  rodzaj polisy,
  data sprzedazy lubezpieczenia,
  data sprzedazy wznowienia,
  
  Jedno z dwóch (cena pierwsza lub cena wznowienia):
    - Jedno z dwóch (cena pakietu lub cena poszczególnych produktów, oba liczą się jako cena pierwsza):
        - cena pakietu,
        - ceny poszczególnych produktów:
            - oc cena,
            - ac cena,
            - cena nnw,
            - cena assistance,
            - gap cena,
    - cena wznowienia,

Reguły normalizacji:
- rocznik zwróć jako rok produkcji pojazdu.
- przebieg zwróć w kilometrach.
- wartosc_pojazdu_brutto i wartosc_pojazdu_netto zwróć w PLN, jeśli są dostępne.
- forma_wlasnosci zwróć tylko wtedy, gdy polisa jednoznacznie wskazuje jedną z wartości: "Własny", "Leasing", "Bank", "Wynajem" lub synonim którejś z nich.
- pojemnosc_silnika zwróć w cm3.
- data_pierwszej_rejestracji dotyczy tylko pojazdów **używanych**; dla pojazdów nowych zwróć "", chyba że polisa jednoznacznie podaje tę datę.
- planowana_data_rejestracji dotyczy tylko pojazdów **nowych**; dla pojazdów używanych zwróć "".
- wspolposiadacz zwróć jako "tak", jeśli polisa wskazuje więcej niż jednego właściciela, współwłaściciela lub współposiadacza pojazdu; zwróć "nie", jeśli polisa jednoznacznie wskazuje tylko jednego właściciela/posiadacza. Jeśli wspolposiadacz to "tak", uzupełnij dane współposiadacza na podstawie polisy.
- pakiet_ubezpieczeniowy zwróć jako "tak", jeśli dokument dotyczy całego pakietu ubezpieczeniowego; zwróć "nie", jeśli dotyczy tylko listy produktów jak AC, NNW, Assistance, GAP albo Przedłużona Gwarancja.
- rodzaj_assistance zwróć tylko wtedy, gdy zakres assistance da się jednoznacznie dopasować do jednej z podanych wartości.
- nr_polisy zwróć jako numer polisy.
- ceny zwróć z walutą, jeśli jest dostępna.
- cena_pakietu dotyczy ceny pakietu za pierwszy rok.
- cena_wznowienia, oc_cena, ac_cena, cena_nnw, cena_assistance, gap_cena i cena_przedluzonej_gwarancji zwróć tylko wtedy, gdy dokument jednoznacznie wskazuje odpowiednią składkę/cenę.
- rodzaj_polisy zwróć tylko wtedy, gdy zakres polisy da się jednoznacznie dopasować do jednej z podanych wartości.
- data_sprzedazy_lubezpieczenia dotyczy sprzedaży ubezpieczenia za pierwszy rok, a data_sprzedazy_wznowienia sprzedaży wznowienia.
- Jeśli dokument podaje "/", "-", "brak", puste pole albo wartość niejednoznaczną, zwróć "".
PROMPT,
    'responseJsonSchema' => [
        'type' => 'object',
        'properties' => [
            'stan_pojazdu' => ['type' => 'string', 'enum' => ['Nowy', 'Używany', 'Nieznany', '']],
            'nr_rejestracyjny' => ['type' => 'string'],
            'marka' => ['type' => 'string'],
            'model' => ['type' => 'string'],
            'wersja' => ['type' => 'string'],
            'vin' => ['type' => 'string'],
            'forma_wlasnosci' => ['type' => 'string', 'enum' => ['Własny', 'Leasing', 'Bank', 'Wynajem', '']],
            'rocznik' => ['type' => 'string'],
            'przebieg' => ['type' => 'string'],
            'wartosc_pojazdu_brutto' => ['type' => 'string'],
            'wartosc_pojazdu_netto' => ['type' => 'string'],
            'kategoria_pojazdu' => [
                'type' => 'string',
                'enum' => [
                    'Osobowy (Kat. M1)',
                    'Ciężarowy - LCV (DMC do 3500kg) Kat. N1',
                    'Motocykle i inne pojazdy (kat.L)',
                    '',
                ],
            ],
            'sposob_korzystania' => ['type' => 'string', 'enum' => ['Standardowy', 'Taxi', '']],
            'typ_silnika' => ['type' => 'string', 'enum' => ['Benzynowy', 'CNG/LPG', 'Diesel', 'Elektryczny', 'Hybryda', '']],
            'pojemnosc_silnika' => ['type' => 'string'],
            'data_nabycia' => ['type' => 'string'],
            'data_pierwszej_rejestracji' => ['type' => 'string'],
            'planowana_data_rejestracji' => ['type' => 'string'],
            'wspolposiadacz' => ['type' => 'string', 'enum' => ['tak', 'nie', '']],
            'imie_wspolposiadacza' => ['type' => 'string'],
            'nazwisko_wspolposiadacza' => ['type' => 'string'],
            'pesel_wspolposiadacza' => ['type' => 'string'],
            'adres_wspolposiadacza' => ['type' => 'string'],
            'pakiet_ubezpieczeniowy' => ['type' => 'string', 'enum' => ['tak', 'nie', '']],
            'rodzaj_assistance' => [
                'type' => 'string',
                'enum' => [
                    'minimalny',
                    'Polska',
                    'Europa (500-700km)',
                    'Europa (1000km)',
                    'Europa (+1500km)',
                    'Inny',
                    '',
                ],
            ],
            'towarzystwo_ubezpieczeniowe' => [
                'type' => 'string',
                'enum' => [
                    'Alianz',
                    'Aviva',
                    'AXA',
                    'Balcia',
                    'Benefia',
                    'Compensa',
                    'Concordia',
                    'Defend',
                    'Ergo Hestia',
                    'Ergo Hestia - Pakiet Dealerski',
                    'Ergo Hestia - Pakiet Dealerski polisa za 1zł',
                    'Euroins',
                    'Generali',
                    'Gothaer',
                    'HDI',
                    'Inne',
                    'Interrisk',
                    'Liberty Ubezpieczenia',
                    'Link4',
                    'Met Life',
                    'MTU',
                    'NN Życie',
                    'Open Life',
                    'PKO Ubezpieczenia',
                    'Polisa - Życie',
                    'Polskie Towarzystwo Reasekuracji',
                    'Proama',
                    'PTU',
                    'PZM',
                    'PZU',
                    'PZU - pakiet dealerski SIGMA',
                    'RESO Europa',
                    'Saltus',
                    'Signal Iduna',
                    'TU Europa',
                    'TUW',
                    'TUZ',
                    'Uniqa',
                    'Vienna Life',
                    'Warta',
                    'Wefox',
                    'Wiener',
                    '',
                ],
            ],
            'nr_polisy' => ['type' => 'string'],
            'data_konca_polisy' => ['type' => 'string'],
            'cena_pakietu' => ['type' => 'string'],
            'cena_wznowienia' => ['type' => 'string'],
            'oc_cena' => ['type' => 'string'],
            'ac_cena' => ['type' => 'string'],
            'cena_nnw' => ['type' => 'string'],
            'cena_assistance' => ['type' => 'string'],
            'gap_cena' => ['type' => 'string'],
            'cena_przedluzonej_gwarancji' => ['type' => 'string'],
            'pochodzenie_polisy' => ['type' => 'string'],
            'rodzaj_polisy' => [
                'type' => 'string',
                'enum' => [
                    'OC',
                    'OC/AC',
                    'OC/AC/NNW',
                    'OC/AC/NNW/Assistance',
                    'AC',
                    'NNW',
                    'Assistance',
                    'GAP',
                    'Przedłużona Gwarancja',
                    '',
                ],
            ],
            'data_sprzedazy_lubezpieczenia' => ['type' => 'string'],
            'data_sprzedazy_wznowienia' => ['type' => 'string'],
        ],
        'required' => [
            'stan_pojazdu',
            'nr_rejestracyjny',
            'marka',
            'model',
            'wersja',
            'vin',
            'forma_wlasnosci',
            'rocznik',
            'przebieg',
            'wartosc_pojazdu_brutto',
            'wartosc_pojazdu_netto',
            'kategoria_pojazdu',
            'sposob_korzystania',
            'typ_silnika',
            'pojemnosc_silnika',
            'data_nabycia',
            'data_pierwszej_rejestracji',
            'planowana_data_rejestracji',
            'wspolposiadacz',
            'imie_wspolposiadacza',
            'nazwisko_wspolposiadacza',
            'pesel_wspolposiadacza',
            'adres_wspolposiadacza',
            'pakiet_ubezpieczeniowy',
            'rodzaj_assistance',
            'towarzystwo_ubezpieczeniowe',
            'nr_polisy',
            'data_konca_polisy',
            'cena_pakietu',
            'cena_wznowienia',
            'oc_cena',
            'ac_cena',
            'cena_nnw',
            'cena_assistance',
            'gap_cena',
            'cena_przedluzonej_gwarancji',
            'pochodzenie_polisy',
            'rodzaj_polisy',
            'data_sprzedazy_lubezpieczenia',
            'data_sprzedazy_wznowienia',
        ],
        'additionalProperties' => false,
    ],
];
